name: Debug Secrets

on:
  workflow_dispatch: # Это позволит запускать его вручную

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print secrets existence
        run: |
          echo "DOCKERHUB_USERNAME is set: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "DOCKERHUB_TOKEN is set: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
          # Следующие строки покажут "***", если секреты существуют, или пусто, если нет
          echo "USERNAME VALUE: '${{ secrets.DOCKERHUB_USERNAME }}'"
          echo "TOKEN VALUE: '${{ secrets.DOCKERHUB_TOKEN }}'"
